from __future__ import annotations

from typing import Any, Iterable, Protocol
from .state import RuntimeSnapshot


class RuntimePort(Protocol):
    scenarios: list[dict]
    missions: list[dict]
    devices: list[dict]
    events: Iterable[dict]
    faults: list[dict]

    def snapshot(self) -> RuntimeSnapshot: ...
    async def start(self) -> None: ...
    async def shutdown(self) -> None: ...
    async def control(self, action: str, speed: float | None = None) -> dict: ...
    async def set_speed(self, speed: float) -> dict: ...
    async def select_scenario(self, scenario_id: str) -> dict: ...
    async def inject_fault(self, request: dict) -> dict: ...
    async def mission_action(self, mission_id: str, action: str) -> dict: ...
    def validate_mission(self, mission_id: str) -> dict: ...
    async def mutate_task(self, payload: dict[str, Any]) -> dict: ...
    async def replan_mission(self, mission_id: str, apply: bool = True) -> dict: ...
    async def device_action(self, device_id: str, action: str) -> dict: ...
    def hil_preflight(self) -> dict: ...
    async def run_hil_sequence(self, sequence_id: str) -> dict: ...
    async def set_recording(self, enabled: bool) -> dict: ...
    def status(self) -> dict: ...
    def telemetry(self) -> dict: ...
